version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: chatbot-analytics-api
    deploy:
      resources:
        limits:
          memory: 512mb
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/chatbot_analytics.db
      - DATASET_DIR=/data/Dataset
      - MODEL_CACHE_DIR=/app/models/cache
      - ALERT_CHANNELS=log
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./models:/app/models
    depends_on: []

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: chatbot-analytics-dashboard
    deploy:
      resources:
        limits:
          memory: 512mb
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./data:/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - api
